"""edited_product_table

Revision ID: 65b715bf85cd
Revises: bfd7959f668d
Create Date: 2022-07-18 18:15:02.663832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b715bf85cd'
down_revision = 'bfd7959f668d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo_url', sa.Text(), nullable=True))
    op.drop_column('products', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'photo_url')
    # ### end Alembic commands ###
