"""edited_clients_table

Revision ID: 98163651ef71
Revises: 9464d79ee6e4
Create Date: 2022-07-15 12:04:28.601797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98163651ef71'
down_revision = '9464d79ee6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'inn',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clients', 'kpp',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'kpp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'inn',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
