"""change_licenses_table

Revision ID: bfd46d3661df
Revises: 32a55eb0bdaf
Create Date: 2022-07-12 11:27:30.273962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd46d3661df'
down_revision = '32a55eb0bdaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('licenses_group_uuid_fkey', 'licenses', type_='foreignkey')
    op.create_foreign_key(None, 'licenses', 'licenses', ['group_id'], ['id'])
    op.drop_column('licenses', 'group_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('group_uuid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'licenses', type_='foreignkey')
    op.create_foreign_key('licenses_group_uuid_fkey', 'licenses', 'licenses', ['group_uuid'], ['id'])
    op.drop_column('licenses', 'group_id')
    # ### end Alembic commands ###
