"""add_columns_user

Revision ID: dd54e590196c
Revises: 9464d79ee6e4
Create Date: 2022-07-16 13:23:00.602714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd54e590196c'
down_revision = '9464d79ee6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('telephone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telephone')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
