"""change_foreign_key_in_licenses

Revision ID: e3c637c5361d
Revises: 9464d79ee6e4
Create Date: 2022-07-16 20:16:05.814381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3c637c5361d'
down_revision = '9464d79ee6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'licenses', 'licenses', ['group_id'], ['id'])
    op.drop_column('licenses', 'group_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('group_uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'licenses', type_='foreignkey')
    op.drop_column('licenses', 'group_id')
    # ### end Alembic commands ###
